# Generated by Django 3.2.5 on 2021-11-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLIGSJP', '0003_proximosestrenos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProximosEstrenos',
        ),
    ]
