# Generated by Django 3.2.5 on 2021-11-23 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPeliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoCategoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CatJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Clasificacion', models.CharField(max_length=10)),
                ('Fecha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CatPeliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Fecha', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoClasificacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProximosEstrenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='VentasPeliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=15)),
                ('FechaCompra', models.CharField(max_length=10)),
                ('Titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLIGSJP.catpeliculas')),
            ],
        ),
        migrations.CreateModel(
            name='VentasJuegos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=15)),
                ('FechaCompra', models.CharField(max_length=10)),
                ('Titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VLIGSJP.catjuegos')),
            ],
        ),
    ]
