# Generated by Django 3.2.5 on 2021-11-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLIGSJP', '0004_delete_proximosestrenos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Tipo', models.CharField(max_length=10)),
            ],
        ),
    ]
