# Generated by Django 3.2.5 on 2021-11-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VLIGSJP', '0005_estrenos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catjuegos',
            name='Fecha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catpeliculas',
            name='Fecha',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventasjuegos',
            name='FechaCompra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventasjuegos',
            name='NombreCliente',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventaspeliculas',
            name='FechaCompra',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ventaspeliculas',
            name='NombreCliente',
            field=models.CharField(max_length=50),
        ),
    ]
