# Generated by Django 3.2.5 on 2021-11-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VLIGSJP', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catjuegos',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='catjuegos',
            name='Clasificacion',
        ),
        migrations.RemoveField(
            model_name='catpeliculas',
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Estrenos',
        ),
        migrations.RemoveField(
            model_name='ventasjuegos',
            name='Titulo',
        ),
        migrations.RemoveField(
            model_name='ventaspeliculas',
            name='Titulo',
        ),
        migrations.DeleteModel(
            name='CategoriaJuegos',
        ),
        migrations.DeleteModel(
            name='CategoriaPeliculas',
        ),
        migrations.DeleteModel(
            name='CatJuegos',
        ),
        migrations.DeleteModel(
            name='CatPeliculas',
        ),
        migrations.DeleteModel(
            name='ClasificacionJuegos',
        ),
        migrations.DeleteModel(
            name='VentasJuegos',
        ),
        migrations.DeleteModel(
            name='VentasPeliculas',
        ),
    ]
